'use client';

import { useState } from 'react';

const privacySections = [
  {
    title: '1. Information We Collect',
    body: 'We collect the information you provide directly, such as your name, email, and trip preferences when you register or use the AI recommendation engine. We also collect usage data — pages visited, trips viewed, and chat interactions with the AI assistant — to improve the platform.',
  },
  {
    title: '2. How We Use Your Information',
    body: 'Your preferences (interests, budget range, travel style) are used solely to power personalized recommendations. Chat history with the AI assistant is used to maintain conversation context and is not sold to third parties. Account information is used for authentication and account management.',
  },
  {
    title: '3. AI Processing',
    body: 'Trip recommendations and chat responses are generated using a third-party large language model provider. Only the data necessary to generate a response (your stated preferences or chat message) is sent for processing, and it is not used by MapMinds to train models beyond your own account experience.',
  },
  {
    title: '4. Data Sharing',
    body: 'We do not sell personal data. We may share limited data with service providers strictly necessary to operate the platform (hosting, database, and AI inference providers), each bound by their own data protection obligations.',
  },
  {
    title: '5. Your Rights',
    body: 'You can update your preferences at any time from the recommendations page, and request account deletion by contacting support@MapMinds.ai. We will remove your personal data within 30 days of a verified request, except where retention is required by law.',
  },
  {
    title: '6. Cookies',
    body: 'We use local storage (not third-party tracking cookies) to keep you signed in and remember your session. No advertising trackers are used on MapMinds.',
  },
];

const termsSections = [
  {
    title: '1. Using MapMinds',
    body: "You must be at least 16 years old to create an account. You agree to provide accurate information when publishing a trip listing and not to post content that is misleading, offensive, or infringes on others' rights.",
  },
  {
    title: '2. User-Published Trips',
    body: 'Trips added through the platform are the responsibility of the user who published them. MapMinds does not verify pricing or availability for user-submitted listings and is not a party to any booking arrangement.',
  },
  {
    title: '3. AI-Generated Content',
    body: 'Recommendations and chat responses are generated by AI and may occasionally be inaccurate or outdated. Always verify critical details (visa requirements, prices, safety advisories) with an official source before booking travel.',
  },
  {
    title: '4. Account Termination',
    body: 'We reserve the right to suspend accounts that violate these terms, including spam, abuse of the AI assistant, or attempts to circumvent platform security.',
  },
];

export default function PrivacyPage() {
  const [activeTab, setActiveTab] = useState<'privacy' | 'terms'>('privacy');

  return (
    <div className="max-w-[800px] mx-auto px-4 md:px-8 py-16 font-body antialiased bg-stone/5 min-h-screen">

      {/* হেডার সেকশন */}
      <div className="mb-10 text-center md:text-left">
        <span className="inline-flex items-center px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-widest bg-black text-white mb-3">
          Legal
        </span>
        <h1 className="font-display text-3xl md:text-4xl font-semibold text-neutral-950 tracking-tight mb-2">
          Privacy Policy & Terms
        </h1>
        <p className="text-xs font-bold uppercase tracking-wider text-neutral-400">
          Last updated: July 2026
        </p>
      </div>

      {/* 🧭 DaisyUI রাউন্ডেড ট্যাব কন্ট্রোল */}
      <div className="tabs tabs-boxed bg-neutral-100/80 p-1.5 rounded-2xl mb-10 border border-neutral-200/40">
        <button
          onClick={() => setActiveTab('privacy')}
          className={`tab flex-1 text-xs font-bold uppercase tracking-wider py-3 rounded-xl transition-all ${activeTab === 'privacy'
            ? 'bg-white text-neutral-950 shadow-xs'
            : 'text-neutral-500 hover:text-neutral-800'
            }`}
        >
          📄 Privacy Policy
        </button>
        <button
          onClick={() => setActiveTab('terms')}
          className={`tab flex-1 text-xs font-bold uppercase tracking-wider py-3 rounded-xl transition-all ${activeTab === 'terms'
            ? 'bg-white text-neutral-950 shadow-xs'
            : 'text-neutral-500 hover:text-neutral-800'
            }`}
        >
          ⚖️ Terms of Service
        </button>
      </div>

      {/* 📜 কন্টেন্ট এরিয়া */}
      <div className="bg-white border border-neutral-200/80 shadow-[0_4px_20px_rgb(0,0,0,0.01)] rounded-[2.5rem] p-6 md:p-10 transition-all duration-300">

        {activeTab === 'privacy' ? (
          <section className="space-y-8 animate-fadeIn">
            {privacySections.map((s) => (
              <div key={s.title} className="group border-b border-neutral-100 last:border-0 pb-6 last:pb-0">
                <h3 className="font-display font-semibold text-neutral-950 text-base md:text-lg tracking-tight mb-2">
                  {s.title}
                </h3>
                <p className="text-sm text-neutral-600 font-medium leading-relaxed">
                  {s.body}
                </p>
              </div>
            ))}
          </section>
        ) : (
          <section className="space-y-8 animate-fadeIn">
            {termsSections.map((t) => (
              <div key={t.title} className="group border-b border-neutral-100 last:border-0 pb-6 last:pb-0">
                <h3 className="font-display font-semibold text-neutral-950 text-base md:text-lg tracking-tight mb-2">
                  {t.title}
                </h3>
                <p className="text-sm text-neutral-600 font-medium leading-relaxed">
                  {t.body}
                </p>
              </div>
            ))}
          </section>
        )}

      </div>

      {/* 📬 ফুটার সাপোর্ট ইনফো */}
      <div className="bg-neutral-50 border border-neutral-200/60 rounded-[1.8rem] p-6 mt-10 flex flex-col sm:flex-row items-center justify-between gap-4 text-center sm:text-left">
        <p className="text-xs font-bold uppercase tracking-wide text-neutral-400">
          Got questions about these policies?
        </p>
        <div className="flex gap-4 text-xs font-bold uppercase tracking-widest">
          <a href="mailto:support@MapMinds.ai" className="text-neutral-950 hover:opacity-75 underline underline-offset-4">
            Email Support
          </a>
          <span className="text-neutral-300">|</span>
          <a href="/contact" className="text-neutral-950 hover:opacity-75 underline underline-offset-4">
            Contact Page
          </a>
        </div>
      </div>

    </div>
  );
}