const sections = [
  {
    title: '1. Information We Collect',
    body:
      'We collect the information you provide directly, such as your name, email, and trip preferences when you register or use the AI recommendation engine. We also collect usage data — pages visited, trips viewed, and chat interactions with the AI assistant — to improve the platform.',
  },
  {
    title: '2. How We Use Your Information',
    body:
      'Your preferences (interests, budget range, travel style) are used solely to power personalized recommendations. Chat history with the AI assistant is used to maintain conversation context and is not sold to third parties. Account information is used for authentication and account management.',
  },
  {
    title: '3. AI Processing',
    body:
      'Trip recommendations and chat responses are generated using a third-party large language model provider. Only the data necessary to generate a response (your stated preferences or chat message) is sent for processing, and it is not used by MapMinds to train models beyond your own account experience.',
  },
  {
    title: '4. Data Sharing',
    body:
      'We do not sell personal data. We may share limited data with service providers strictly necessary to operate the platform (hosting, database, and AI inference providers), each bound by their own data protection obligations.',
  },
  {
    title: '5. Your Rights',
    body:
      'You can update your preferences at any time from the recommendations page, and request account deletion by contacting support@MapMinds.ai. We will remove your personal data within 30 days of a verified request, except where retention is required by law.',
  },
  {
    title: '6. Cookies',
    body:
      'We use local storage (not third-party tracking cookies) to keep you signed in and remember your session. No advertising trackers are used on MapMinds.',
  },
];

const terms = [
  {
    title: '1. Using MapMinds',
    body:
      "You must be at least 16 years old to create an account. You agree to provide accurate information when publishing a trip listing and not to post content that is misleading, offensive, or infringes on others' rights.",
  },
  {
    title: '2. User-Published Trips',
    body:
      'Trips added through the platform are the responsibility of the user who published them. MapMinds does not verify pricing or availability for user-submitted listings and is not a party to any booking arrangement.',
  },
  {
    title: '3. AI-Generated Content',
    body:
      'Recommendations and chat responses are generated by AI and may occasionally be inaccurate or outdated. Always verify critical details (visa requirements, prices, safety advisories) with an official source before booking travel.',
  },
  {
    title: '4. Account Termination',
    body:
      'We reserve the right to suspend accounts that violate these terms, including spam, abuse of the AI assistant, or attempts to circumvent platform security.',
  },
];

export default function PrivacyPage() {
  return (
    <div className="container-page py-12 max-w-3xl">
      <h1 className="text-3xl md:text-4xl font-bold text-neutral-900 mb-3">Privacy Policy & Terms of Service</h1>
      <p className="text-neutral-500 mb-10">Last updated: July 2026</p>

      <section className="mb-12">
        <h2 className="text-xl font-semibold text-neutral-900 mb-5">Privacy Policy</h2>
        <div className="space-y-6">
          {sections.map((s) => (
            <div key={s.title}>
              <h3 className="font-medium text-neutral-900 mb-1">{s.title}</h3>
              <p className="text-sm text-neutral-600 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-neutral-900 mb-5">Terms of Service</h2>
        <div className="space-y-6">
          {terms.map((t) => (
            <div key={t.title}>
              <h3 className="font-medium text-neutral-900 mb-1">{t.title}</h3>
              <p className="text-sm text-neutral-600 leading-relaxed">{t.body}</p>
            </div>
          ))}
        </div>
      </section>

      <p className="text-sm text-neutral-500 mt-12">
        Questions about this policy? Contact us at{' '}
        <a href="mailto:support@MapMinds.ai" className="text-primary hover:underline">support@MapMinds.ai</a> or visit our{' '}
        <a href="/contact" className="text-primary hover:underline">contact page</a>.
      </p>
    </div>
  );
}
